DROP TABLE CHARACTER;

CREATE TABLE "CHARACTERS" (
    "NO"    NUMBER PRIMARY KEY,
	"NAME"	    NVARCHAR2(6)  NOT NULL,
    "ALIAS"      NVARCHAR2(6)  NOT NULL,
	"BIRTHDAY"	    DATE NOT NULL,
	"DESCRIPTION"   VARCHAR2(100), 
	"DEL_FLAG"	    CHAR(1)	    DEFAULT 'N'	CHECK(DEL_FLAG IN ('Y', 'N')) NOT NULL,
	"AUTHORITY"	        NUMBER	 DEFAULT 1  CHECK(AUTHORITY IN (1, 2)) NOT NULL, 
    "PICTURE"       NVARCHAR2(100)
);

COMMENT ON COLUMN "CHARACTERS"."NO" IS '번호';
COMMENT ON COLUMN "CHARACTERS"."NAME" IS '이름';
COMMENT ON COLUMN "CHARACTERS"."ALIAS" IS '별명';
COMMENT ON COLUMN "CHARACTERS"."BIRTHDAY" IS '생년월일(8자리)';
COMMENT ON COLUMN "CHARACTERS"."DESCRIPTION" IS '설명';
COMMENT ON COLUMN "CHARACTERS"."DEL_FLAG" IS '삭제 여부(Y:삭제, N:삭제X)';
COMMENT ON COLUMN "CHARACTERS"."AUTHORITY" IS '권한(1:관리자, 2:일반)';


INSERT INTO CHARACTERS VALUES(1, '승연', '연승', '19981010','쫄보다.' ,'N' , 1, '연승.png');
INSERT INTO CHARACTERS VALUES(2,  '수연', '빡수', '19980325','승연보다 더한 쫄보다.' ,'N' , 1, '빡수.png');
INSERT INTO CHARACTERS VALUES(3, '예은', '예은', '19950504','제일 용감하다.' ,'N' , 2, '예은.png');
INSERT INTO CHARACTERS VALUES(4,'지혜', '지혜', '20040113','가장 쫄보다.' ,'N' , 2, '지혜.png');

SELECT * FROM CHARACTERS;